name: BetterFurnaces
description: Adds left-click functionality to furnaces based on item in hand
authors: [RedNifre, daemitus]
main: com.daemitus.betterfurnaces.BetterFurnaces
version: 1.1.0 (unofficial RedNifre fork)